name: Update Markdown and Generate

on:
  push:
    branches:
      - site

jobs:
  update_markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Copy Markdown files from master
        run: |
          # Create a temporary directory for markdown files
          mkdir -p markdown_temp
          # Checkout master branch and copy all .md files
          git checkout master
          cp *.md markdown_temp/
          # Switch back to the site branch
          git checkout site

      - name: Clone docs-generator repository
        run: |
          git clone https://github.com/LotousOrganization/docs-generator.git
          cd docs-generator
          composer install

      - name: Create markdown directory in docs-generator
        run: |
          mkdir -p docs-generator/markdown

      - name: Move Markdown files to docs-generator
        run: |
          mv markdown_temp/*.md docs-generator/markdown/
          
      - name: Run PHP generator script
        run: |
          cd docs-generator
          php generate.php

      - name: Update index.html in site branch
        run: |
          # Copy the new index.html from output to the root of the site branch
          cp docs-generator/output/index.html .
          
      - name: Commit and push changes to site branch
        run: |
          git add index.html
          git commit -m "Update index.html with the latest generated version"
          git push origin site
