name: Update Markdown and Generate

on:
  push:
    branches:
      - master

jobs:
  update_markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Copy Markdown files from master
        run: |
          # Create a temporary directory for markdown files
          mkdir -p markdown_temp
          # Copy all .md files from master branch
          cp *.md markdown_temp/

      - name: Clone docs-generator repository
        run: |
          git clone https://github.com/LotousOrganization/docs-generator.git
          cd docs-generator
          composer install

      - name: Create markdown directory in docs-generator
        run: |
          mkdir -p docs-generator/markdown

      - name: Move Markdown files to docs-generator
        run: |
          mv markdown_temp/*.md docs-generator/markdown/
          
      - name: Run PHP generator script
        run: |
          cd docs-generator
          php generate.php

      - name: Update index.html in site branch
        run: |
          # Copy the new index.html from output to the root of the site branch
          cp docs-generator/output/index.html .

      - name: Configure Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Commit and push changes to site branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the personal access token
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/beephp/docs.git
          git add index.html
          git commit -m "Update index.html with the latest generated version"
          git push origin site
